# The Python Programming Language: Function 

In [1]:
x = 1 
y = 2 
x + y 

3

In [2]:
x

1

In [1]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))



Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


## Reading and writing data files

In [6]:
import csv 

%precision 2 

with open('mpg.csv') as csvfile: 
    mpg = list(csv.DictReader(csvfile))

mpg[:3] # The first three dictionaries in our list

[{'': '1',
  'class': 'compact',
  'cty': '18',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'auto(l5)',
  'year': '1999'},
 {'': '2',
  'class': 'compact',
  'cty': '21',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m5)',
  'year': '1999'},
 {'': '3',
  'class': 'compact',
  'cty': '20',
  'cyl': '4',
  'displ': '2',
  'drv': 'f',
  'fl': 'p',
  'hwy': '31',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m6)',
  'year': '2008'}]

In [7]:
len(mpg)

234

In [9]:
mpg[0].keys()

['',
 'trans',
 'displ',
 'hwy',
 'cty',
 'drv',
 'year',
 'model',
 'manufacturer',
 'fl',
 'class',
 'cyl']

In [10]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [11]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

In [12]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [14]:
CtyMpgByCyl = []
for c in cylinders: #iterates over all the cylinder levels
    summpg = 0 
    cyltypecount = 0 
    for d in mpg: #iterate over all dictionares
        if d['cyl'] == c: #if the cylinder level type matches 
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 #increment the count 
    CtyMpgByCyl.append((c,summpg/cyltypecount)) # append the tuple 
CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

## Date and TImes 

In [15]:
import datetime as dt
import time as tm 

In [16]:
tm.time()

1477357371.67

In [17]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2016, 10, 24, 18, 3, 11, 289976)

In [18]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour

(2016, 10, 24, 18)

In [19]:
delta = dt.timedelta(days = 100)
delta 

datetime.timedelta(100)

In [20]:
today = dt.date.today()

In [21]:
today - delta 

datetime.date(2016, 7, 16)

In [22]:
class Person: 
    department = 'School of Information' #class variable
    
    def set_name(self,new_name): 
        self.name = new_name 
    def set_location(self, new_location): 
        self.location = new_location 

In [23]:
person = Person()

In [26]:
person.set_name('Kris Anaya')
person.set_location('Sacrament, Ca, USA')
print('{} live in {} and works nowhere').format(person.name,person.location)

Kris Anaya live in Sacrament, Ca, USA and works nowhere


In [27]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [28]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [36]:
['a','b']  + [ 1,2]

['a', 'b', 1, 2]

In [39]:
import numpy as np

In [37]:
type(lambda x: x+1)

function

In [47]:
array = np.arange(36).reshape(6,6)

In [44]:
array[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [45]:
array[::7]

array([[0, 1, 2, 3, 4, 5]])

In [46]:
array[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [48]:
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [49]:
array.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [50]:
array[[2,3],[2,3]]

array([14, 21])

In [51]:
array[2::2,2::2]

array([[14, 16],
       [26, 28]])

In [54]:
array[2:4,2:4]

array([[14, 15],
       [20, 21]])